apiVersion: apps/v1
kind: Deployment
metadata:
  name: "apigateway-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "apigateway-app"
  template:
    metadata:
      labels:
        app: "apigateway-app"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: apigateway-container
        image: ghcr.io/superellips/apigateway:c7cc2e5152591a448f8ef5799d8f86a6d10ca397
        # resources:
        #   limits:
        #     cpu: "10"
        #     memory: "100Mi"
        #   requests:
        #     cpu: "10 "
        #     memory: "50Mi"
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: apigateway-config