apiVersion: apps/v1
kind: Deployment
metadata:
  name: "apigateway-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "apigateway-app"
  template:
    metadata:
      labels:
        app: "apigateway-app"
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: apigateway-container
        image: ghcr.io/superellips/apigateway:d0dc2296fc63a3d039c28fdcbb50f58e31d9b83d
        # resources:
        #   limits:
        #     cpu: "10"
        #     memory: "100Mi"
        #   requests:
        #     cpu: "10 "
        #     memory: "50Mi"
        ports:
        - containerPort: 8080
        envFrom: 
        - configMapRef:
            name: apigateway-config